### ISSUE TITLE
Linearized Liquid Neural Networks

### ISSUE THREAD

**Issue by jean-moorman** [raminmh/liquid-s4#21]
Hi Ramin,

I am wondering why a linearized version of liquid neural network was used, would a nonlinear version no longer be considered a state-space model? I am confused whether there was a theoretical reason to use linear LNNs or whether it was to follow more closely in the vein of SSM literature.

Thanks,
Jean

**Comment by raminmh** [comment]
the LTC formulation is a nonlinear input-varying state-space model. You can scale LTCs but with nontrivial methods. This is the most expressive continous time RNN.


The Liquid-S4 (Hasani et al. 2022) is a linear time- and input- varying state-space model. this one can scale efficiently because it is a linear model. Mamba is a hardware optimized version of Liquid-S4.
